- name: dependencies
  ansible.builtin.pip:
    name: "{{item}}"
  with_items:
    - boto3
    - docopt

- name: nfs-utils
  ansible.builtin.dnf:
    name: nfs-utils

- name: cluster instance setup
  ansible.builtin.copy:
    src: cluster_instance_setup.py
    dest: /usr/local/bin/
    mode: 0755

- name: cluster instance setup
  ansible.builtin.copy:
    src: attach_random_volume.py
    dest: /usr/local/bin/
    mode: 0755
